### PR TITLE
Add BL-Touch throughs timer conflict error message

### PR DESCRIPTION
**Pull request by Virtual-Java**
### Description

First I tried to compile then CR6Community and after I spent the last two days in adopting pmatsol58s code to newest version of marlin I finally found your repository again:-)
Is it correct that your code is based on these repos?
https://github.com/CR6Community/Marlin ;   https://github.com/Pmatsol58/VyperCE6.1

After I created a Pull-Request to merge (my tries to merge above code into the most recent version of marlin causing linking errors) yesterday, https://github.com/CR6Community/Marlin/pull/349 , I tried to add support for BL-Touch using CR6Community, VyperCE6.1 as well as your repo Vyper_MB_CE_6.2 today.

Today I tried to add support for BL-Touch using your version of marlin but entered the same 'One or more timer are in conflict' error as yesterday with the other versions.

How can I solve these timer-issues and support BLtouch on a STM32F103 Tri-Gorilla V006 board?
Unfortunately my motherboard (original Vyper Tri-Gorilla V006 board) is using the GD32F103RET6 instead of the STM32F103.
I have already modified my motherboard a lot (adding a mosfet, several resistors, a screw terminal and a LED to support a second heater, Heater1), did a stealthBurner mod and more but the most clearly option to modify this board should be to support USB natively since there are places for 22-68Ohmes series resistors for native USB which are currently not assembled.
So it should be possible to add support for native USB instead of the serial to USB conversion.
Consequently there will be options for USB-OTG (USB-HumanInputDevice HID) plug and play (CH341 requires special drivers) and to connect to the computer the mainboard as MassStorageDevice.

But in this Pull request I only ask on how to solve the 'timer conflict' in order to support BL-Touch?

I invested many time to combine the StealthBurner mod with BLtouch in behind the nozzle, change to your community-firmware, adopted my Vyper to use a Glassbed of less size originally intended for use with CrealityEnder or CR6 and now I want to speed up support for Marlin and Vyper. I will invest some more time in testing the firmware, adding support for different hardware (Relays-switched-dual-extruder, XOR-Gate shared dual filament movement sensors or a wired-or/wired-and Filament-runout-Sensor) as well as support of native USB (Vyper uses a CH341 bridge but native USB DN and DP can be connected via 22Ohmes to the USB-B receptacle.)

### Requirements

BL-Touch

### Benefits

Replace the unreliable strain-gauge by a more reliable BL-Touch sensor.
Replace the CH321 by native USB to support plug & play as well as to add the ability to interact with the computer as mass storage device to put files on.

### Configurations

See the only commit in this PR

### Related Issues

Bed leveling with strain-gauge is bad because it does not support StealthBurner modification and it is not that reliable.
Timer error although a definition '#define TEMP_TIMER  5' is already in your configuration for Tri-Gorilla-Mainboard

### CODE REVIEW

**Comment by rommulaner** [comment]
My 6.2 is based on Marlin 2.1.2.1 and is a further development of the 6.1. I implemented all needed changes in Marlin to get the CE run on that version and that took some time.
I tried a bit around and implemented your changes in my test environment and got it compiled with no errors.
Can you test the attached firmware if it works?
[main_board_20240310-140856_BLTOUCH.zip](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2/files/14550298/main_board_20240310-140856_BLTOUCH.zip)

**Comment by Virtual-Java** [comment]
Thank you a lot for getting this compiled.
Using this software I am able to start the auto leveling process. Then it heats up my printing head to exact 145°C and the HeatingBed to 60°C. Then my printing head moves to the center of the printing bed and tells me I should apply Z offset in center and move the nozzle down to the correct distance (so that a piece of paper is fitting in between the nozzle and my printing bed).
Unfortunately then both target temperatures are set to 0°C, the one of the nozzle and the one of the bed, but these values are not possible unless I move with my printer to a more northern country and use it in my garden house.:-)

After around half an hour, my printer is still hanging in the center of my build plate and waits until a temperature of zero degree celcius is reached.
BL-Touch is clicking all the time (that is something that has happened even before your update, so it should be normal) and moves its pin up and down two times a second.

So I think there is a issue with a setting to heat the nozzle during probing or not.

What settings did you use to get these software compiled for BL-Touch???

Thank you very much for examining how to fix the timer error.

**Comment by rommulaner** [comment]
You need to comment PROBE_TARE and change the lines 131 to 133 in the buildroot\share\PlatformIO\variants\MARLIN_F103Rx\variant.h to 

#ifdef TIMER_SERVO
  #undef TIMER_SERVO
  #define TIMER_SERVO           TIM2  // TIMER_SERVO must be defined in this file
#endif

I don't know if the TIMER 2 is the right one, but it should be correct as it works.

About the temp drop you should deactivate BETTER ACCURACY in the leveling setting menu, then the heaters stay active during probing.

**Comment by rommulaner** [comment]
Any response here? Did it work?

**Comment by Virtual-Java** [comment]
Hi rommulaner,
finally I got it work today. I checked my wiring and i found the sensor pin SIG on my MainBoard was connected to the analog output of my temperature-sensor instead of the output of BLTouch.
Resoldering the connection finally fixed my issues.

But I got other issues related to BLTouch. Because I use a glass bed for Creality Ender3 which is fixed with small selfmade angles published on [thingiverse](https://www.thingiverse.com/thing:6154132) and consequently my printing area is a bit smaller than usual. To fix the offsets to make the nozzle fit to the glass bed and do never get outside the printing area for all four edges was not possible using the only definitions of "X/Y_MIN_POS" and "X/Y_MAX_POS". I had to change "MANUAL_X/Y_HOME_POS" and add an additional X/Y_MAX_OFFSET.
And most important. It is not possible for the nozzle to get outside the right and the left edge, even for manual drive. in calculation of X/Y_MAX_POS. Therefore I added the X/Y_MAX_OFFSET. Maybe this is wrong, but at least my printer is working now.

If you want you can add an #ifdef GLASSBED_CREALITY construction to my to allow BL_Touch to keep within the lower sized 230 x 230 mm Glassbed with effective printing area of approx. 224 x 224 mm.

Thank you very much for helping me in getting BL_Touch work for this printer. I have to get some experience now and tell you then what works on my heavily modified Vyper printer.

**Pull request closed without merging**
